config/routes.rb
Crowdfunding::Application.routes.draw do
  get "/home",     to: 'pages#home',      as: 'home'
  get "/contact",  to: 'pages#contact',   as: 'contact'
  get "/about",    to: 'pages#about',     as: 'about'
  get "/blog",     to: 'pages#blog',      as: 'blog'


  resources :sessions, :only => [:new, :create, :destroy]

  get    "/sign_up",  to: 'users#sign_up',       as: 'sign_up'
  get    "/sign_in",  to: 'sessions#new',        as: 'sign_in'
  delete "/sign_out", to: 'sessions#destroy',    as: 'sign_out'

  get "pages/definition"

  resources :projects
  resources :users do
    resources :projects
  end

  root :to => "pages#home"

  #Route use by madrill-rails gem for webhook implementation
  resource :inbox, :controller => 'inbox', :only => [:show,:create]

  get '*unmatched_route', :to => 'application#raise_not_found!'
  get ':not_found' => redirect('/'), :constraints => { :not_found => /.*/ }

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  first_name      :string(255)
#  last_name       :string(255)
#  email           :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#  password_digest :string(255)
#  admin :boolean, default: false
#

class User < ActiveRecord::Base
	has_many :projects, dependent: :destroy
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  has_secure_password

	validates :first_name, :last_name, presence: :true, :length => {:minimum => 3, :maximum => 20}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, :uniqueness => { case_sensitive: false }
  validates :password, length: { minimum: 6 }, :on => :create

  def self.search(search)
    if search
      find(:all, :conditions => ['first_name LIKE ?' , "%#{search}%"])
    else
      find(:all)
    end
  end

  def pretty_name
    "#{self.first_name} #{self.last_name}"
  end

  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def self.digest_token
    User.digest(User.new_remember_token)
  end

  def feed
    projects
  end

private

  def create_remember_token
    self.remember_token = User.digest_token
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper

  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  # GET /users
  def index
    @title = app_title('All users')
    @users = User.order(created_at: :desc).paginate(page: params[:page],:per_page=> 10)
  end

  # GET /users/1
  def show
    @title = app_title(@user.pretty_name)
    @projects = @user.projects.paginate(page: params[:page])
  end

  # GET /users/new
  def new
    @title = app_title('New user')
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @title = app_title('Edit user')
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      sign_in(@user)
      redirect_to @user, :flash => { success: Settings.page_home_main_welcome_message }
      UserMailer.delay.welcome(@user)
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, :flash => { success: 'User was successfully updated.'}
    else
      render action: 'edit'
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, :flash => { success: 'User was successfully destroyed.'}
  end

  def sign_up
    @title = app_title('Sign up')
    @user = User.new
  end

  private

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end

    # Before filters

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/views/users/_form.html.haml
= simple_form_for @user, :html => { :class => 'form-horizontal' } do |f|
  .row-fluid
    .span8.offset1
      = render 'shared/error_messages', object: f.object
  .row-fluid
    .span8.offset1
      = field_set_tag do
        = f.input :first_name
        = f.input :last_name
        = f.input :email
        = f.input :password
        = f.input :password_confirmation, label: 'Confirmation'
      .form-actions
        = f.button :submit, :class => 'btn-primary'
        = link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn'
    .span2
      .thumbnail
        .caption
          .picture-profile
            = link_to "http://gravatar.com/emails" do
              <i class="fa fa-pencil fa-fw"></i>
            = @user.email.nil? ? image_tag("frontend/profile-default.png") : gravatar_for(@user, size: 200)
          %h3 Picture
          .form-actions
            = link_to t('.change', :default => t("helpers.links.change")), "http://gravatar.com/emails", :class => 'btn'


:javascript
  document.getElementById('user_first_name').focus();

app/views/users/edit.html.haml
- model_class = User
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize, :default => "Update your profile"
= render :partial => 'form'

app/views/users/index.html.haml
- model_class = User
.page-header
  %h1= t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped.table-hover
  %thead
    %tr
      %th=  model_class.human_attribute_name(:id)
      %th First & Last Name
      %th Project(s)
      %th= t '.actions', :default => t("helpers.actions")
  %tbody
    - cpt = 0
    - @users.each do |user|
      %tr
        %td= "#{cpt+=1}"
        %td
          = link_to gravatar_for(user, size: 52), user_path(user), :'data-toggle' => 'tooltip', :'data-placement'=> 'top', :title => user.pretty_name
          = link_to user.pretty_name, user_path(user), :'data-toggle' => 'tooltip', :'data-placement'=> 'top', :title => user.pretty_name
        %td
          - if user.projects.any?
            = link_to user_projects_path(user), :'data-toggle' => 'tooltip', :'data-placement'=> 'top', :title => 'View projects' do
              <i class='fa fa-eye'></i>
        %td
          - if current_user.admin? or current_user?(user)
            = link_to edit_user_path(user),  :'data-toggle' => 'tooltip', :'data-placement'=> 'top', :title => t('.edit', :default => t("helpers.links.edit")) do
              <i class="fa fa-pencil fa-fw"></i>
          - if current_user.admin? && !current_user?(user)
            |
            = link_to user_path(user), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },  :'data-toggle' => 'tooltip', :'data-placement'=> 'top', :title => t('.destroy', :default => t("helpers.links.destroy")) do
              <i class="fa fa-trash-o fa-fw"></i>
    = will_paginate @users
= link_to t('.new', :default => t("helpers.links.new")), new_user_path, :class => 'btn btn-primary'

app/views/users/new.html.haml
- model_class = User
.page-header
  %h1= t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/users/show.html.haml
- model_class = User
- model_class2 = Project
.row-fluid
  .span3
    %section
      %h3
        = gravatar_for @user
        = @user.first_name
  .span9
    .page-header
    <!-- Nav tabs -->
    %ul.nav.nav-tabs
      %li.active= link_to "Projects (#{@user.projects.count})", "#projects", "data-toggle" => "tab"
      %li= link_to "Feed", "#feed", "data-toggle" => "tab"
      %li= link_to "Statistics ", "#statistics ", "data-toggle" => "tab"

    <!-- Tab panes -->
    .tab-content
      .tab-pane.active#projects
        .caption
        - if @user.projects.any?
          %ol.projects
            = render @projects
          = will_paginate @projects
      .tab-pane#feed
        Feed
      .tab-pane#statistics
        Statistics

app/views/users/sign_up.html.haml
- model_class = User
.content
  .page-header
    %h1= t '.Sign_up', :default => [:'helpers.titles.sign_up', 'Sign up %{model}'], :model => model_class.model_name.human.titleize
  = render :partial => 'form'