config/routes.rb
Crowdfunding::Application.routes.draw do
  get "/home",     to: 'pages#home',      as: 'home'
  get "/contact",  to: 'pages#contact',   as: 'contact'
  get "/about",    to: 'pages#about',     as: 'about'
  get "/blog",     to: 'pages#blog',      as: 'blog'


  resources :sessions, :only => [:new, :create, :destroy]

  get    "/sign_up",  to: 'users#sign_up',       as: 'sign_up'
  get    "/sign_in",  to: 'sessions#new',        as: 'sign_in'
  delete "/sign_out", to: 'sessions#destroy',    as: 'sign_out'

  get "pages/definition"

  resources :projects
  resources :users do
    resources :projects
  end

  root :to => "pages#home"

  #Route use by madrill-rails gem for webhook implementation
  resource :inbox, :controller => 'inbox', :only => [:show,:create]

  get '*unmatched_route', :to => 'application#raise_not_found!'
  get ':not_found' => redirect('/'), :constraints => { :not_found => /.*/ }

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  description :text
#  user_id     :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Project < ActiveRecord::Base
	belongs_to :user
  validates :description, presence: true
  validates :title, presence: true,  :length => {:minimum => 5, :maximum => 50}
  validates :user_id, presence: true

  scope :owner, -> (user_id) { where("user_id = ?", user_id.to_i) }
  default_scope -> { order('created_at DESC') }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include ApplicationHelper
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user, only: [:new, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /projects
  def index
    @title = app_title('Projects Feed')
    @projects = Project.owner(params[:user_id]).paginate(page: params[:page],:per_page=> 5) if params[:user_id]
    @projects ||= Project.all.paginate(page: params[:page],:per_page=> 5)
  end

  # GET /projects/1
  def show
    # @projects  = current_user.projects.build
    # @feed_items = current_user.feed.paginate(page: params[:page]) if signed_in?
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  def create
    @project = current_user.projects.build(project_params) unless !signed_in?
    @project ||=  Project.new(project_params)

    if @project.save
      redirect_to @project, :flash => { success: 'Project was successfully created.'}
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /projects/1
  def update
    if @project.update(project_params)
      redirect_to @project, :flash => { success: 'Project was successfully updated.'}
    else
      render action: 'edit'
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    redirect_to user_projects_path(current_user), :flash => { success: 'Project was successfully destroyed.' }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def project_params
      params.require(:project).permit(:title, :description, :user_id)
    end

    def correct_user
      @project = Project.find(params[:id])
      redirect_to(root_url) unless current_user?(@project.user)
    end
end

app/views/projects/_form.html.haml
= simple_form_for @project, :html => { :class => 'form-horizontal' } do |f|
  = f.input :title
  = f.input :description
  / f.association :user, label_method: :pretty_name, value_method: :id
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), projects_path, :class => 'btn'


:javascript
  document.getElementById('project_title').focus();

app/views/projects/_project.html.haml
%li
  %h5.title= link_to project.title, project_path(project)
  .description= project.description.truncate(100)
  .timestamp
    = "Posted #{time_ago_in_words(project.created_at)} ago."

app/views/projects/edit.html.haml
- model_class = Project
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/projects/index.html.haml
- model_class = Project
.page-header
  %h1= t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th N°
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:user)
      %th= t '.actions', :default => t("helpers.actions")
    %tr
  %thead
  %tbody
    - cpt = 0
    - @projects.each do |project|
      %tr
        %td= link_to "#{cpt+=1}", project_path(project)
        %td= project.title
        %td= project.description
        %td= link_to project.user.pretty_name, user_path(project.user)
        %td
          - if signed_in? && current_user.admin? && current_user?(project.user)
            = link_to edit_project_path(project), :'data-toggle' => 'tooltip', :'data-placement'=> 'top', :title => t('.edit', :default => t("helpers.links.edit")) do
              <i class="fa fa-pencil fa-fw"></i>
            = link_to project_path(project), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },  :'data-toggle' => 'tooltip', :'data-placement'=> 'top', :title => t('.destroy', :default => t("helpers.links.destroy")) do
              <i class="fa fa-trash-o fa-fw"></i>
    = will_paginate @projects
= link_to t('.new', :default => t("helpers.links.new")), new_project_path, :class => 'btn btn-primary'

app/views/projects/new.html.haml
- model_class = Project
.page-header
  %h1= t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/projects/show.html.haml
- model_class = Project
.page-header
  %h1= t '.title', :default => model_class.model_name.human.titleize
.project-row
  %dl.dl-horizontal
    %dt
      %strong= model_class.human_attribute_name(:title) + ":"
    %dd= @project.title
    %dt
      %strong= model_class.human_attribute_name(:description) + ":"
    %dd= @project.description
    %dt
      %strong= model_class.human_attribute_name(:user) + ":"
    %dd= @project.user.pretty_name

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), projects_path, :class => 'btn'
  - if signed_in? && current_user?(@project.user)
    = link_to t('.edit', :default => t("helpers.links.edit")), edit_project_path(@project), :class => 'btn'
    = link_to t('.destroy', :default => t("helpers.links.destroy")), project_path(@project), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'