config/routes.rb
Crowdfunding::Application.routes.draw do
  get "/home",     to: 'pages#home',      as: 'home'
  get "/contact",  to: 'pages#contact',   as: 'contact'
  get "/about",    to: 'pages#about',     as: 'about'
  get "/blog",     to: 'pages#blog',      as: 'blog'


  resources :sessions, :only => [:new, :create, :destroy]

  get    "/sign_up",  to: 'users#sign_up',       as: 'sign_up'
  get    "/sign_in",  to: 'sessions#new',        as: 'sign_in'
  delete "/sign_out", to: 'sessions#destroy',    as: 'sign_out'

  get "pages/definition"

  resources :projects
  resources :users do
    resources :projects
  end

  root :to => "pages#home"

  #Route use by madrill-rails gem for webhook implementation
  resource :inbox, :controller => 'inbox', :only => [:show,:create]

  get '*unmatched_route', :to => 'application#raise_not_found!'
  get ':not_found' => redirect('/'), :constraints => { :not_found => /.*/ }

end

app/views/layouts/_body_header.html.erb
<div class="navbar navbar-inverse navbar-fluid-top" >
  <div class="navbar-inner container-top-navbar">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/"><%= Settings.application_name %></a>
      <div class="container-fluid nav-collapse">
        <ul class="nav">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", about_path  %></li>
          <li><%= link_to "Contact", contact_path  %></li>
           <li><%= link_to "Blog", blog_path %></li>
        </ul>
        <ul class="nav navbar-nav pull-right">
          <% if signed_in? %>
            <li>
              <%= link_to user_projects_path(current_user) do %>
              <i class="fa fa-briefcase"></i> Projects
              <%end%>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= gravatar_for(current_user, size: 30) %> <b class="caret"></b></a>
              <ul class="dropdown-menu dropdown-menu-item">
                <li>
                  <%= link_to current_user do %>
                  <i class="fa fa-user fa-fw"></i> Profile
                  <%end%>
                </li>
                <li>
                  <%= link_to edit_user_path(current_user)   do %>
                  <i class="fa fa-cog"></i> Settings
                  <%end%>
                </li>
                <li class="divider"></li>
                <li>
                   <%= link_to sign_out_path, :method => :delete do %>
                    <i class="fa fa-sign-out"></i> Sign out
                  <%end%>
                </li>
              </ul>
            </li>
          <%else%>
          <li>
            <%= link_to sign_in_path do %>
              <i class="fa fa-sign-in fa-fw"></i> Sign in
            <%end%>
          </li>
          <%end%>
          <li>
            <%= link_to about_path do %>
            <i class="fa fa-info-circle"></i> Help
            <%end%>
          </li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/_body_side_bar.html.erb
<div class="well sidebar-nav">
  <ul class="nav nav-list">
    <li class="nav-header">Sidebar</li>
    <li><%= link_to "Link1", "/path1"  %></li>
    <li><%= link_to "Link2", "/path2"  %></li>
    <li><%= link_to "Link3", "/path3"  %></li>
  </ul>
</div><!--/.well -->

app/views/layouts/_head.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><%= content_for?(:title) ? yield(:title) : @title %></title>
<%= csrf_meta_tags %>

<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
<![endif]-->

<%= stylesheet_link_tag "application", :media => "all", "data-turbolinks-track" => true  %>

<!-- For third-generation iPad with high-resolution Retina display: -->
<!-- Size should be 144 x 144 pixels -->
<%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

<!-- For iPhone with high-resolution Retina display: -->
<!-- Size should be 114 x 114 pixels -->
<%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

<!-- For first- and second-generation iPad: -->
<!-- Size should be 72 x 72 pixels -->
<%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

<!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
<!-- Size should be 57 x 57 pixels -->
<%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

<!-- For all other devices -->
<!-- Size should be 32 x 32 pixels -->
<%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

<%= javascript_include_tag "application", "data-turbolinks-track" => true %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= render 'layouts/head'%>
  <head>
  <body>
    <%= render 'layouts/body_header'%>
    <div class="container">
        <div class="main-content">
          <%= flash_messages %>
          <%= yield %>
        </div><!--/main-content-->
    </div> <!-- /container -->
    <footer>
      <%= render 'layouts/body_footer'%>
    </footer>
     <%= debug(params) if Rails.env.development? %>
  </body>
</html>